spring:
  datasource:
      jdbc-url: jdbc:postgresql://localhost:55432/digital-signage
      username: postgres
      password: docker
#      driver-class-name : org.postgresql.Driver
      hikari :
        minimumIdle : 5
        maximumPoolSize : 20
        idleTimeout : 30000
        poolName : SpringBootJPAHikariCP
        maxLifetime : 2000000
        connectionTimeout : 30000
  jpa :
    hibernate :
      ddl-auto: none
    properties :
      hibernate :
        show_sql : true
        format_sql: true
        temp :
          use_jdbc_metadata_defaults: false
        dialect  : org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url       : ${spring.datasource.jdbc-url}
    user      : ${spring.datasource.username}
    password  : ${spring.datasource.password}

# Enable logging
#logging:
#  level:
#    root : DEBUG
#    org.hibernate.SQL: WARN
#    com.zaxxer.hikari.HikariConfig: WARN